name: Build, Test and Deploy (dev)

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

env:
  LIBNAPC_DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
  LIBNAPC_DEPLOY_URL: ${{ secrets.DEPLOY_URL }}

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install Dependencies
      run: |
         sudo apt-get update
         sudo apt install gcc make gcc-aarch64-linux-gnu binutils-aarch64-linux-gnu
         sudo apt install gcc-x86-64-linux-gnu
         sudo apt install valgrind

    - name: Build source
      run: ./build.scripts/build.php

    - name: Run Unit Tests
      run: ./ci.run-tests.sh

    - name: Export documentation
      run: cd documentation-site/ && ./export.sh

    - name: Deploy
      run: ./ci.deploy.php
