name: Build and Test (dev)

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install Dependencies
      run: |
         sudo apt-get update
         sudo apt install gcc make gcc-aarch64-linux-gnu binutils-aarch64-linux-gnu
         sudo apt install gcc-x86-64-linux-gnu

    - name: Build source
      run: ./build.scripts/build.php

    - name: Unit tests
      run: ./ci.run-tests.sh
