name: Build and Test

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install Dependencies
      run: |
         sudo apt-get update
         sudo apt install gcc make
         sudo apt install valgrind
         sudo apt install fakeroot-ng

    - name: Run CI-Script
      run: ./.napci/run.sh
