name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  NAPPHP_LOAD_PATH: /home/runner/napphp/src/__load.php

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install Dependencies
      run: |
         sudo apt-get update
         sudo apt install gcc make
         sudo apt install valgrind
         sudo apt install fakeroot-ng

    - name: Install napphp
      run: |
         mkdir ~/napphp
         git clone --depth 1 --branch v0.0.1 'https://github.com/nap-software/napphp.git' ~/napphp

    - name: Run CI-Script
      run: env ; cat "$NAPPHP_LOAD_PATH" ; ./.napci/run.sh
